machine:
  environment:
    USER_NAME: bigjonroberts
    USER_EMAIL: bigjonroberts@gmail.com
  ruby:
    version: 2.4.1
  node:
    version: 8.2.1

dependencies:
  pre:
    - ./bin/setup

test:
  post:
    - bundle exec jekyll build
    - bundle exec htmlproofer ./_site --only-4xx --allow-hash-href

deployment:
  production:
    branch: master
    commands:
      - ./bin/automated
